### ISSUE TITLE
Images with orientation error

### ISSUE THREAD

**Issue by popod** [davej/electron-image-resize#4]
When an image has an [orientation](http://sylvana.net/jpegcrop/exif_orientation.html) (5, 6, 7 or 8), it's width and height property are inverted. Should test exif orientation before resize !

**Comment by davej** [comment]
I'll accept a PR if you want to do this but I'm happy to naively do whatever Chromium does for the moment as I don't need exif orientation support. Also, image resize will be in the next version of Electron (https://github.com/electron/electron/pull/7488) at which point this module will be deprecated.

**Comment by popod** [comment]
Okey, thanks for reply. So I will wait on Electron.
